"use strict";
const assert = require("assert/strict");
const { FoundationBoard } = require("./foundationBoard");
let passed = 0;
async function test(name, fn) { let timer; try { await Promise.race([fn(), new Promise((_, reject) => { timer = setTimeout(() => reject(new Error("Test did not settle: " + name)), 2000); })]); passed++; console.log("ok - " + name); } finally { clearTimeout(timer); } }
function deferred() { let resolve, reject; const promise = new Promise((a,b) => { resolve=a; reject=b; }); return {promise,resolve,reject}; }
function detail(slug, revision=1) { return {business:{id:slug,slug},canvas:{revision,snapshot:{nodes:[],edges:[]}}}; }
function fixture(overrides={}) {
 const messages=[]; const client={listBusinesses:async()=>({ok:true,businesses:[]}),getBusinessDetail:async s=>detail(s),pollEvents:async()=>({events:[],cursor:'next'}),saveCanvas:async()=>({ok:true}),...overrides};
 const board=new FoundationBoard(client,m=>messages.push(m));return {board,client,messages};
}
(async()=>{
 await test('empty successful board is delivered as data',async()=>{const f=fixture();await f.board.refresh();assert.deepEqual(f.messages[0].state.board.businesses,[]);});
 await test('board timeout exposes error',async()=>{const f=fixture({listBusinesses:async()=>{throw Error('timeout');}});await f.board.refresh();assert.equal(f.messages[0].type,'error');});
 await test('out-of-order selection cannot replace current business',async()=>{const a=deferred();const f=fixture({getBusinessDetail:s=>s==='a'?a.promise:Promise.resolve(detail(s))});const old=f.board.show('a');await f.board.show('b');a.resolve(detail('a'));await old;assert.equal(f.board.detail.business.slug,'b');assert.equal(f.messages.filter(m=>m.type==='detail').length,1);});
 await test('back invalidates pending detail and polling',async()=>{const d=deferred();const f=fixture({getBusinessDetail:()=>d.promise});const p=f.board.show('a');f.board.back();d.resolve(detail('a'));await p;assert.equal(f.board.detail,null);assert.equal(f.messages.filter(m=>m.type==='detail').length,0);});
 await test('stale errors do not poison a new selection',async()=>{const d=deferred();const f=fixture({getBusinessDetail:s=>s==='a'?d.promise:Promise.resolve(detail(s))});const p=f.board.show('a');await f.board.show('b');d.reject(Error('old timeout'));await p;assert.equal(f.messages.filter(m=>m.type==='error').length,0);});
 await test('disposed panel receives no pending board response',async()=>{const d=deferred();const f=fixture({listBusinesses:()=>d.promise});const p=f.board.refresh();f.board.dispose();d.resolve({businesses:[]});await p;assert.equal(f.messages.length,0);});
 await test('polls never overlap',async()=>{let calls=0;const d=deferred();const f=fixture({pollEvents:()=>{calls++;return d.promise;}});await f.board.show('a');const p=f.board.poll();await f.board.poll();assert.equal(calls,1);d.resolve({events:[]});await p;});
 await test('all business events refresh the projection',async()=>{let loads=0;const f=fixture({getBusinessDetail:async s=>{loads++;return detail(s);},pollEvents:async()=>({events:[{business_id:'a',event_type:'connection.updated'}],cursor:'2'})});await f.board.show('a');await f.board.poll();assert.equal(loads,2);assert.equal(f.board.cursor,'2');});
 await test('failed projection does not advance cursor; retry catches it',async()=>{let fail=false;const f=fixture({getBusinessDetail:async s=>{if(fail)throw Error('offline');return detail(s,2);},pollEvents:async()=>({events:[{business_id:'a'}],cursor:'2'})});await f.board.show('a');const old=f.board.cursor;fail=true;await f.board.poll();assert.equal(f.board.cursor,old);assert.equal(f.messages.at(-1).type,'error');fail=false;await f.board.poll();assert.equal(f.board.cursor,'2');assert.equal(f.messages.at(-1).type,'connection');});
 await test('recovery refetches even without new events',async()=>{let calls=0,offline=true;const f=fixture({getBusinessDetail:async s=>{calls++;return detail(s);},pollEvents:async()=>{if(offline)throw Error('offline');return {events:[]};}});await f.board.show('a');await f.board.poll();offline=false;await f.board.poll();assert.equal(calls,2);});
 await test('navigation during poll ignores old cursor and events',async()=>{const d=deferred();const f=fixture({pollEvents:()=>d.promise});await f.board.show('a');const old=f.board.cursor;const p=f.board.poll();await f.board.show('b');d.resolve({events:[{business_id:'a'}],cursor:'stale'});await p;assert.equal(f.board.cursor,old);assert.equal(f.board.detail.business.slug,'b');});
 await test('duplicate canvas submissions produce one write',async()=>{let writes=0;const d=deferred();const f=fixture({saveCanvas:()=>{writes++;return d.promise;}});await f.board.show('a');const p=f.board.addNode('a','note','id');await f.board.addNode('a','note','id2');assert.equal(writes,1);d.resolve({ok:true});await p;assert.equal(f.messages.filter(m=>m.type==='saved').length,1);});
 await test('wrong business cannot receive a node',async()=>{let writes=0;const f=fixture({saveCanvas:async()=>{writes++;}});await f.board.show('a');await f.board.addNode('b','note','id');assert.equal(writes,0);assert.equal(f.messages.find(m=>m.type==='error').type,'error');});
 await test('revision conflict retains draft and does not auto overwrite',async()=>{let writes=0;const f=fixture({saveCanvas:async()=>{writes++;throw Error('HTTP 409');}});await f.board.show('a');await f.board.addNode('a','note','id');assert.equal(writes,1);assert.equal(f.board.saving,false);assert.equal(f.messages.filter(m=>m.type==='saved').length,0);assert.match(f.messages.find(m=>m.type==='error').message,/409/);});
 await test('canonical save carries expected revision and stable mutation id',async()=>{let args;const f=fixture({saveCanvas:async(...a)=>{args=a;}});await f.board.show('a');await f.board.addNode('a',' שלום ','id');assert.equal(args[2],1);assert.equal(args[3],'id');assert.equal(args[1].nodes[0].title,'שלום');});
 await test('leaving during a write cannot reopen the business',async()=>{const d=deferred();const f=fixture({saveCanvas:()=>d.promise});await f.board.show('a');const p=f.board.addNode('a','note','id');f.board.back();d.resolve({ok:true});await p;assert.equal(f.board.detail,null);assert.equal(f.messages.filter(m=>m.type==='detail').length,1);});
 await test('stale poll cannot overwrite an acknowledged canvas save',async()=>{const d=deferred();let revision=1;const f=fixture({pollEvents:()=>d.promise,getBusinessDetail:async s=>detail(s,revision),saveCanvas:async()=>{revision=2;}});await f.board.show('a');const p=f.board.poll();await f.board.addNode('a','note','id');d.resolve({events:[{business_id:'a'}],cursor:'old'});await p;assert.equal(f.board.detail.canvas.revision,2);assert.notEqual(f.board.cursor,'old');});
 await test('derived image data is not copied into canonical write',async()=>{let saved;const d=detail('a');d.canvas.snapshot.nodes=[{id:'image',imageUrl:'/api/foundation/imagine/assets/a/x.png',imageDataUri:'data:image/png;base64,AAAA'}];const f=fixture({getBusinessDetail:async()=>d,saveCanvas:async(_s,snapshot)=>{saved=snapshot;}});await f.board.show('a');await f.board.addNode('a','note','id');assert.equal(saved.nodes[0].imageDataUri,undefined);assert.equal(saved.nodes[0].imageUrl,d.canvas.snapshot.nodes[0].imageUrl);assert.equal(d.canvas.snapshot.nodes[0].imageDataUri,'data:image/png;base64,AAAA');});
 await test('disposed session starts no further requests',async()=>{let calls=0;const f=fixture({listBusinesses:async()=>{calls++;return {businesses:[]};},getBusinessDetail:async s=>{calls++;return detail(s);}});f.board.dispose();await f.board.refresh();await f.board.show('a');await f.board.poll();assert.equal(calls,0);});
 await test('uncertain save retries the same mutation and snapshot',async()=>{const writes=[];const f=fixture({saveCanvas:async(...a)=>{writes.push(a);if(writes.length===1)throw Error('connection reset after apply');}});await f.board.show('a');await f.board.addNode('a','note','first');await f.board.addNode('a','note','new');assert.equal(writes.length,2);assert.equal(writes[1][3],'first');assert.deepEqual(writes[0][1],writes[1][1]);});
 await test('definite conflict rebuilds against refreshed revision',async()=>{const writes=[];let revision=1;const f=fixture({getBusinessDetail:async s=>detail(s,revision),saveCanvas:async(...a)=>{writes.push(a);if(writes.length===1)throw Object.assign(Error('conflict'),{statusCode:409});}});await f.board.show('a');await f.board.addNode('a','note','first');revision=2;await f.board.show('a');await f.board.addNode('a','note','next');assert.equal(writes[1][2],2);assert.equal(writes[1][3],'next');});
 console.log(`foundationBoard.test.js: ${passed}/${passed} passed`);
})().catch(e=>{console.error(e);process.exitCode=1;});
