"use strict";
// Mercury commerce bridge — pure helpers shared by the IDE controller and tests.
//
// The stored connector credential is "<baseURL>|<store_id>". On build the IDE
// drops a typed client (lib/mercury.ts) into the project so the storefront
// talks to the live Mercury engine (genesis/commerce/server.mjs) instead of
// mock data. Every route below mirrors a route that really exists in Mercury:
//   GET  /api/stores/:id/products          catalog (variants + images hydrated)
//   POST /api/stores/:id/checkout          { items:[{variant_id, qty}], discount_code?, email?, sid? }
//   POST /api/collect                      analytics pixel collector (store_id, sid, type, path, ref, dur_ms)
//   GET  /pixel.js?data-store=<id>         first-party pixel script
// Mercury has NO single-product GET route, so getProduct() resolves through the
// catalog. Analytics never accepts "purchase" from the client — the engine
// attributes purchases server-side.

function parseMercuryCredential(raw) {
	const text = String(raw || "").trim();
	if (!text) return null;
	const [base, storeId] = text.split("|").map((x) => (x || "").trim());
	if (!base || !storeId) return null;
	if (!/^https?:\/\//i.test(base)) return null;
	if (!/^str_[a-z0-9]+$/i.test(storeId)) return null;
	return { base: base.replace(/\/+$/, ""), storeId };
}

function mercuryClientSource(cfg) {
	if (!cfg || !cfg.base || !cfg.storeId) throw new Error("mercury config required");
	return [
		"// Auto-generated by Solstice — Mercury commerce connector (headless).",
		"// Customer storefront only: never render store analytics/revenue to shoppers.",
		"export const MERCURY_BASE = " + JSON.stringify(cfg.base) + ";",
		"export const STORE_ID = " + JSON.stringify(cfg.storeId) + ";",
		"export const PIXEL_SRC = MERCURY_BASE + '/pixel.js';",
		"export type MercuryVariant = { id: string; title: string; sku: string; price_cents: number; stock: number };",
		"export type MercuryProduct = { id: string; title: string; description: string; image: string; images?: string[]; status: string; options?: any[]; variants: MercuryVariant[] };",
		"export type CartItem = { variant_id: string; qty: number };",
		"export type CheckoutResult = { session_id: string; provider: 'stripe' | 'mock'; total_cents: number; url: string; applied_rules?: any[]; free_shipping?: boolean };",
		"async function api<T = any>(path: string, init?: RequestInit): Promise<T> {",
		"  const r = await fetch(MERCURY_BASE + path, { ...(init || {}), headers: { 'Content-Type': 'application/json', ...((init && (init.headers as any)) || {}) } });",
		"  if (!r.ok) throw new Error('Mercury ' + path + ' ' + r.status);",
		"  return r.json() as Promise<T>;",
		"}",
		"export const getProducts = (): Promise<MercuryProduct[]> => api<MercuryProduct[]>('/api/stores/' + STORE_ID + '/products');",
		"// Mercury exposes no GET /products/:id — resolve through the catalog.",
		"export const getProduct = async (id: string): Promise<MercuryProduct | null> => (await getProducts()).find((p) => p.id === id) || null;",
		"export const createCheckout = (items: CartItem[], extra?: { discount_code?: string; email?: string; sid?: string }): Promise<CheckoutResult> =>",
		"  api<CheckoutResult>('/api/stores/' + STORE_ID + '/checkout', { method: 'POST', body: JSON.stringify({ items, ...(extra || {}) }) });",
		"export const validateDiscount = (code: string, subtotal_cents: number) =>",
		"  api('/api/stores/' + STORE_ID + '/discounts/validate', { method: 'POST', body: JSON.stringify({ code, subtotal_cents }) });",
		"// Analytics goes to the engine-wide collector with the pixel schema; purchase is server-attributed and rejected from clients.",
		"function visitorSid(): string {",
		"  try { const ss = globalThis.sessionStorage; let sid = ss.getItem('mrc_sid'); if (!sid) { sid = Math.random().toString(16).slice(2, 18); ss.setItem('mrc_sid', sid); } return sid; } catch { return 'srv'; }",
		"}",
		"export const trackEvent = (type: string, payload?: Record<string, unknown>): Promise<void> => {",
		"  if (!type || type === 'purchase') return Promise.resolve();",
		"  const body = JSON.stringify({ store_id: STORE_ID, sid: visitorSid(), type: String(type).slice(0, 32), path: (typeof location !== 'undefined' ? location.pathname + location.search : ''), payload: payload || null });",
		"  return fetch(MERCURY_BASE + '/api/collect', { method: 'POST', body, keepalive: true }).then(() => undefined).catch(() => undefined);",
		"};",
		"",
	].join("\n");
}

// The generated file is TypeScript; static (non-TS) projects get the same client as
// plain ESM so a vanilla page can `import { getProducts } from './lib/mercury.js'`.
function mercuryClientSourceJs(cfg) {
	return mercuryClientSource(cfg)
		.split("\n")
		.filter((line) => !/^export type /.test(line))
		.map((line) => line
			.replace(/async function api<T = any>\(path: string, init\?: RequestInit\): Promise<T>/, "async function api(path, init)")
			.replace(/return r\.json\(\) as Promise<T>;/, "return r.json();")
			.replace(/api<[A-Za-z\[\]]+>\(/g, "api(")
			.replace(/\(\): Promise<MercuryProduct\[\]> =>/, "() =>")
			.replace(/async \(id: string\): Promise<MercuryProduct \| null> =>/, "async (id) =>")
			.replace(/\(items: CartItem\[\], extra\?: \{[^}]*\}\): Promise<CheckoutResult> =>/, "(items, extra) =>")
			.replace(/\(code: string, subtotal_cents: number\) =>/, "(code, subtotal_cents) =>")
			.replace(/function visitorSid\(\): string/, "function visitorSid()")
			.replace(/\(type: string, payload\?: Record<string, unknown>\): Promise<void> =>/, "(type, payload) =>")
			.replace(/\(init && \(init\.headers as any\)\)/, "(init && init.headers)"))
		.join("\n");
}


// --- Opening a store from the IDE ----------------------------------------------
// Mercury has no auth on its loopback API (the owner UI gates it behind a session);
// the IDE talks to the engine directly. Everything below mirrors real routes:
//   GET  /api/health                         { ok:true, engine:"mercury" }
//   POST /api/stores                         { name, vertical?, currency? } -> 201 store
//   GET  /api/stores/:id                     store row
//   GET  /api/stores/:id/products            catalog
//   POST /api/stores/:id/products            { title, description?, image?, images?, variants:[{title?,sku?,price_cents,stock?}] } -> 201
const MERCURY_DEFAULT_BASE = "http://127.0.0.1:8791";
const MERCURY_CURRENCIES = ["ILS", "USD", "EUR"];
const MERCURY_SEED_FILE = ".solstice/mercury/seed.json";
const MERCURY_SEEDED_FILE = ".solstice/mercury/seeded.json";

function formatMercuryCredential(base, storeId) {
	const cfg = parseMercuryCredential(String(base || "") + "|" + String(storeId || ""));
	if (!cfg) throw new Error("invalid mercury base/store id");
	return cfg.base + "|" + cfg.storeId;
}

function normalizeMercuryBase(raw) {
	const text = String(raw || "").trim().replace(/\/+$/, "");
	if (!text) return MERCURY_DEFAULT_BASE;
	if (!/^https?:\/\/[^\s|]+$/i.test(text)) throw new Error("כתובת Mercury חייבת להתחיל ב-http(s):// — " + text);
	return text;
}

async function mercuryFetchJson(fetchImpl, url, init) {
	const doFetch = fetchImpl || globalThis.fetch;
	if (typeof doFetch !== "function") throw new Error("fetch unavailable");
	const r = await doFetch(url, { signal: AbortSignal.timeout(15000), ...(init || {}), headers: { "content-type": "application/json", ...((init && init.headers) || {}) } });
	let body = null;
	try { body = await r.json(); } catch { body = null; }
	return { status: r.status, ok: r.ok, body };
}

// Health probe: the engine must answer and identify itself — a random HTTP server
// on the pasted address (or a Next dev server) must not pass as Mercury.
async function mercuryHealth(base, fetchImpl) {
	const b = normalizeMercuryBase(base);
	let res;
	try { res = await mercuryFetchJson(fetchImpl, b + "/api/health"); }
	catch (e) { throw new Error("Mercury לא עונה ב-" + b + " — " + (e && e.message || e)); }
	if (!res.ok || !res.body || res.body.ok !== true || res.body.engine !== "mercury") throw new Error("הכתובת " + b + " אינה מנוע Mercury (health " + res.status + ")");
	return { base: b, stripe: !!res.body.stripe };
}

function normalizeStoreSpec(spec) {
	const name = String((spec && spec.name) || "").trim().replace(/\s+/g, " ");
	if (!name) throw new Error("שם חנות נדרש");
	if (name.length > 120) throw new Error("שם חנות ארוך מדי (עד 120 תווים)");
	const currency = String((spec && spec.currency) || "ILS").trim().toUpperCase();
	if (!/^[A-Z]{3}$/.test(currency)) throw new Error("מטבע חייב להיות קוד ISO של 3 אותיות — " + currency);
	const vertical = String((spec && spec.vertical) || "").trim().slice(0, 80);
	return { name, currency, vertical };
}

// Open a brand-new store on the engine and return the credential the vault stores.
async function openMercuryStore(base, spec, fetchImpl) {
	const health = await mercuryHealth(base, fetchImpl);
	const body = normalizeStoreSpec(spec);
	const res = await mercuryFetchJson(fetchImpl, health.base + "/api/stores", { method: "POST", body: JSON.stringify(body) });
	if (res.status !== 201 || !res.body || typeof res.body.id !== "string") throw new Error("פתיחת החנות נכשלה (" + res.status + ") " + ((res.body && res.body.error) || ""));
	if (!/^str_[a-z0-9]+$/i.test(res.body.id)) throw new Error("המנוע החזיר מזהה חנות לא צפוי: " + res.body.id);
	return { store: res.body, base: health.base, storeId: res.body.id, credential: formatMercuryCredential(health.base, res.body.id) };
}

async function mercuryStoreStatus(cfg, fetchImpl) {
	if (!cfg || !cfg.base || !cfg.storeId) throw new Error("mercury config required");
	const store = await mercuryFetchJson(fetchImpl, cfg.base + "/api/stores/" + cfg.storeId);
	if (store.status === 404) throw new Error("החנות " + cfg.storeId + " לא קיימת ב-" + cfg.base);
	if (!store.ok || !store.body) throw new Error("Mercury store " + store.status);
	const products = await mercuryFetchJson(fetchImpl, cfg.base + "/api/stores/" + cfg.storeId + "/products");
	if (!products.ok || !Array.isArray(products.body)) throw new Error("Mercury products " + products.status);
	return { id: store.body.id, name: store.body.name, currency: store.body.currency, vertical: store.body.vertical || "", products: products.body.length };
}

// Seed file written by Felix: { products: [{ title, description?, image?, images?, variants: [{ title?, sku?, price_cents, stock? }] }] }.
// Validation is total before any network call, so a bad seed never half-creates a catalog.
function validateMercurySeed(seed) {
	const list = seed && Array.isArray(seed.products) ? seed.products : null;
	if (!list) throw new Error("seed.json: נדרש מערך products");
	if (!list.length) throw new Error("seed.json: products ריק");
	const titles = new Set();
	return list.map((p, i) => {
		const where = "seed.json products[" + i + "]";
		const title = String((p && p.title) || "").trim();
		if (!title) throw new Error(where + ": title חסר");
		if (titles.has(title)) throw new Error(where + ": title כפול — " + title);
		titles.add(title);
		const variants = Array.isArray(p.variants) ? p.variants : [];
		if (!variants.length) throw new Error(where + ": נדרש לפחות variant אחד");
		const variantKeys = new Set();
		const vs = variants.map((v, j) => {
			const w = where + ".variants[" + j + "]";
			const price = v && v.price_cents;
			if (!Number.isSafeInteger(price) || price < 0) throw new Error(w + ": price_cents חייב להיות מספר שלם ≥ 0");
			const stock = v.stock === undefined ? 0 : v.stock;
			if (!Number.isSafeInteger(stock) || stock < 0) throw new Error(w + ": stock חייב להיות מספר שלם ≥ 0");
			const title = String((v && v.title) || "Default").trim() || "Default", sku = String((v && v.sku) || "").trim();
			const key = sku ? "sku:" + sku : "title:" + title;
			if (variantKeys.has(key)) throw new Error(w + ": variant כפול — " + key);
			variantKeys.add(key);
			return { title, sku, price_cents: price, stock };
		});
		const images = Array.isArray(p.images) ? p.images.map((x) => String(x || "").trim()).filter(Boolean) : [];
		const image = String((p && p.image) || images[0] || "").trim();
		return { title, description: String((p && p.description) || ""), image, images: images.length ? images : (image ? [image] : []), variants: vs };
	});
}

// Merge named products/variants without deleting variants or changing their IDs.
// Mercury's edit endpoint replaces the variants list, so include untouched rows.
function mercuryProductUpdate(product, current, previous, supplied, preservedInventory) {
	const patch = {};
	for (const key of ["description", "image", "images"]) {
		if (!Object.hasOwn(supplied, key) && !(key === "images" && Object.hasOwn(supplied, "image")) && !(key === "image" && Object.hasOwn(supplied, "images"))) continue;
		if (JSON.stringify(product[key]) !== JSON.stringify(current[key]) && (!previous || JSON.stringify(product[key]) !== JSON.stringify(previous[key]))) patch[key] = product[key];
	}
	const variants = (current.variants || []).map(v => ({ ...v }));
	let changed = false;
	const used = new Set();
	for (const [index, v] of product.variants.entries()) {
		const matches = variants.filter(x => v.sku ? x.sku === v.sku : x.title === v.title);
		if (matches.length > 1) throw new Error("Mercury: variant לא חד-משמעי — " + product.title + " / " + (v.sku || v.title));
		const match = matches[0];
		if (match && used.has(match.id)) throw new Error("Mercury: variant כפול — " + product.title);
		if (match) used.add(match.id);
		const prior = previous && previous.variants.find(x => v.sku ? x.sku === v.sku : x.title === v.title);
		if (!match) { variants.push(v); changed = true; continue; }
		for (const key of ["title", "sku", "price_cents", "stock"]) {
			if (!Object.hasOwn(supplied.variants[index], key)) continue;
			// On first adoption (including legacy receipts), inventory belongs to
			// the engine. Only a subsequent explicit seed change may restock it.
			if (key === "stock" && !prior) {
				if (match.stock !== v.stock) preservedInventory.push({ product: product.title, variant: v.sku || v.title, requested: v.stock, actual: match.stock });
				continue;
			}
			// An unrelated content edit must not reset inventory after a sale.
			if (match[key] !== v[key] && (!prior || prior[key] !== v[key])) { match[key] = v[key]; changed = true; }
		}
	}
	if (changed) patch.variants = variants;
	return patch;
}

// Serialize writes from this extension host to each engine/store. This is not a
// server-side idempotency guarantee across separate IDE processes.
const mercurySeedQueues = new Map();
async function withMercuryQueue(cfg, action) {
	if (!cfg || !cfg.base || !cfg.storeId) throw new Error("mercury config required");
	const key = JSON.stringify([normalizeMercuryBase(cfg.base), cfg.storeId]);
	const previous = mercurySeedQueues.get(key) || Promise.resolve();
	const current = previous.catch(() => {}).then(action);
	mercurySeedQueues.set(key, current);
	try { return await current; }
	finally { if (mercurySeedQueues.get(key) === current) mercurySeedQueues.delete(key); }
}
async function seedMercuryStore(cfg, seed, fetchImpl) {
	return withMercuryQueue(cfg, () => seedMercuryStoreUnlocked(cfg, seed, fetchImpl));
}

async function seedMercuryStoreUnlocked(cfg, seed, fetchImpl, previousProducts) {
	if (!cfg || !cfg.base || !cfg.storeId) throw new Error("mercury config required");
	const products = validateMercurySeed(seed);
	const live = await mercuryFetchJson(fetchImpl, cfg.base + "/api/stores/" + cfg.storeId + "/products");
	if (live.status === 404) throw new Error("החנות " + cfg.storeId + " לא קיימת ב-" + cfg.base);
	if (!live.ok || !Array.isArray(live.body)) throw new Error("Mercury products " + live.status);
	// Prepare the whole plan first: ambiguity must never partially edit a catalog.
	const preservedInventory = [];
	const plan = products.map((p, index) => {
		const matches = live.body.filter(x => String(x.title || "").trim() === p.title);
		if (matches.length > 1) throw new Error("Mercury: title לא חד-משמעי — " + p.title);
		const current = matches[0];
		const previous = (previousProducts || []).find(x => x.title === p.title);
		return { p, current, patch: current ? mercuryProductUpdate(p, current, previous, seed.products[index], preservedInventory) : p };
	});
	const created = [], updated = [], skipped = [], expected = [];
	for (const { p, current, patch } of plan) {
		if (current && !Object.keys(patch).length) { skipped.push(p.title); continue; }
		const res = await mercuryFetchJson(fetchImpl, cfg.base + "/api/stores/" + cfg.storeId + "/products" + (current ? "/" + encodeURIComponent(current.id) : ""), { method: "POST", body: JSON.stringify(patch) });
		if (res.status !== (current ? 200 : 201) || !res.body || !res.body.id || (current && res.body.id !== current.id)) throw new Error("סנכרון המוצר «" + p.title + "» נכשל (" + res.status + ")");
		(current ? updated : created).push({ id: res.body.id, title: p.title });
		expected.push({ id: res.body.id, patch });
	}
	if (expected.length) {
		const check = await mercuryFetchJson(fetchImpl, cfg.base + "/api/stores/" + cfg.storeId + "/products");
		if (!check.ok || !Array.isArray(check.body)) throw new Error("Mercury: קריאה חוזרת נכשלה");
		for (const { id, patch } of expected) {
			const actual = check.body.find(x => x.id === id);
			if (!actual || Object.entries(patch).some(([key, value]) => key === "variants"
				? value.some(v => { const a = actual.variants.find(x => v.id ? x.id === v.id : v.sku ? x.sku === v.sku : x.title === v.title); return !a || ["title", "sku", "price_cents", "stock"].some(k => a[k] !== v[k]); })
				: JSON.stringify(actual[key]) !== JSON.stringify(value))) throw new Error("Mercury: הנתונים שנקראו מחדש אינם תואמים למוצר " + id);
		}
	}
	return { created, updated, skipped, total: live.body.length + created.length, products, preservedInventory };
}

// Build-time sync: if the project carries .solstice/mercury/seed.json, push it once per
// (store, seed-content) and record the receipt in seeded.json. Returns null when there is
// nothing to do; never throws on a missing seed, always throws on a bad one.
async function syncMercurySeedFromProject(root, cfg, fetchImpl, deps) {
	const fs = (deps && deps.fs) || require("node:fs"), path = (deps && deps.path) || require("node:path");
	if (!root || !fs.existsSync(path.join(root, MERCURY_SEED_FILE))) return null;
	const run = async () => {
		const hash = require("node:crypto").createHash("sha256").update(fs.readFileSync(path.join(root, MERCURY_SEED_FILE))).digest("hex");
		const statusPath = path.join(root, ".solstice/mercury/sync-status.json");
		const record = value => fs.writeFileSync(statusPath, JSON.stringify({ hash, at: new Date().toISOString(), ...value }, null, 2) + "\n");
		record({ status: "pending" });
		try {
			if (!cfg || !cfg.storeId) throw new Error("חבר חנות Mercury לפני סנכרון המוצרים");
			const receipt = await syncMercurySeedUnlocked(root, cfg, fetchImpl, deps);
			record({ status: "passed", created: receipt.created.length, updated: (receipt.updated || []).length, unchanged: !!receipt.unchanged, preservedInventory: receipt.preservedInventory || [] });
			return receipt;
		} catch (error) {
			record({ status: "failed", error: String(error.message || error).slice(0, 800) });
			throw error;
		}
	};
	return cfg && cfg.storeId ? withMercuryQueue(cfg, run) : run();
}

function mercurySyncStatus(root) {
	const fs = require("node:fs"), path = require("node:path"), crypto = require("node:crypto");
	if (!root || !fs.existsSync(path.join(root, MERCURY_SEED_FILE))) return null;
	try {
		const state = JSON.parse(fs.readFileSync(path.join(root, ".solstice/mercury/sync-status.json"), "utf8"));
		const hash = crypto.createHash("sha256").update(fs.readFileSync(path.join(root, MERCURY_SEED_FILE))).digest("hex");
		return { ...state, status: state.hash !== hash ? "stale" : ["passed", "failed"].includes(state.status) ? state.status : "unverified" };
	} catch { return { status: "unverified" }; }
}
async function syncMercurySeedUnlocked(root, cfg, fetchImpl, deps) {
	const fs = (deps && deps.fs) || require("node:fs");
	const path = (deps && deps.path) || require("node:path");
	const crypto = (deps && deps.crypto) || require("node:crypto");
	if (!root || !cfg || !cfg.storeId) return null;
	const seedPath = path.join(root, MERCURY_SEED_FILE);
	if (!fs.existsSync(seedPath)) return null;
	const raw = fs.readFileSync(seedPath, "utf8");
	const hash = crypto.createHash("sha256").update(raw).digest("hex");
	const seededPath = path.join(root, MERCURY_SEEDED_FILE);
	let prev;
	try {
		prev = JSON.parse(fs.readFileSync(seededPath, "utf8"));
		if (prev && prev.version === 2 && prev.base === cfg.base && prev.storeId === cfg.storeId && prev.hash === hash) return { ...prev, unchanged: true };
	} catch { }
	let seed;
	try { seed = JSON.parse(raw); } catch (e) { throw new Error("seed.json אינו JSON תקין — " + (e && e.message || e)); }
	const prior = prev && prev.version === 2 && prev.base === cfg.base && prev.storeId === cfg.storeId ? prev.products : null;
	const result = await seedMercuryStoreUnlocked(cfg, seed, fetchImpl, prior);
	const receipt = { version: 2, storeId: cfg.storeId, base: cfg.base, hash, at: new Date().toISOString(), ...result };
	fs.mkdirSync(path.dirname(seededPath), { recursive: true });
	fs.writeFileSync(seededPath, JSON.stringify(receipt, null, 2) + "\n");
	return receipt;
}

module.exports = {
	parseMercuryCredential, mercuryClientSource, mercuryClientSourceJs,
	MERCURY_DEFAULT_BASE, MERCURY_CURRENCIES, MERCURY_SEED_FILE, MERCURY_SEEDED_FILE,
	formatMercuryCredential, normalizeMercuryBase, mercuryHealth, openMercuryStore, mercuryStoreStatus,
	validateMercurySeed, seedMercuryStore, syncMercurySeedFromProject, mercurySyncStatus,
};
