'use strict';
const assert=require('assert/strict'),fs=require('fs'),path=require('path'),os=require('os'),Module=require('module');
const {sourceRevision}=require('./sourceRevision'),{projectReadiness,acceptanceContext}=require('./projectReadiness');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'felix-acceptance-'));let count=0;const deadline=setTimeout(()=>{console.error('acceptance timeout');process.exit(1);},15000);
async function test(name,fn){await fn();count++;console.log('ok - '+name);}
(async()=>{try{
 fs.mkdirSync(path.join(root,'.solstice'));fs.writeFileSync(path.join(root,'app.js'),'original');fs.writeFileSync(path.join(root,'.solstice','design-contract.json'),JSON.stringify({version:1}));
 const file=path.join(__dirname,'extension.js'),m=new Module(file,module);m.filename=file;m.paths=module.paths;const original=m.require.bind(m);m.require=id=>id==='vscode'?{workspace:{workspaceFolders:[{uri:{fsPath:root}}]}}:original(id);m._compile(fs.readFileSync(file,'utf8')+'\nmodule.exports.Controller=AgentController;',file);
 const valid={ok:true,url:'http://127.0.0.1:3000/',summary:{linksChecked:1,buttonsChecked:1,formsChecked:1,desktopWidth:1440,mobileWidth:390},findings:[]};
 function fixture(report){const c=Object.create(m.exports.Controller.prototype),sent=[],failed=[];c._browserSelfCheck={id:'test',token:'token',round:0,maxRounds:3};c.browserSelfCheckUrl=async()=>valid.url;c.resolveWalkthroughRuntime=()=>({bin:process.execPath,env:{}});c.context={extensionPath:__dirname};c.output={append(){}};c.announceAgentMessage=()=>{};c._learningSignals=new Map();c.post=()=>{};c.fleetFlow=()=>{};c.maybeCreateWalkthrough=()=>{};c.drainSteerQueue=()=>{};c.send=async t=>sent.push(t);c.failBrowserSelfCheck=(_s,t)=>failed.push(t);c.runCli=async(_bin,args)=>{if(args.includes('check')&&args[0].endsWith('project-check.js')){const dir=args.at(-1);fs.mkdirSync(dir,{recursive:true});if(report)fs.writeFileSync(path.join(dir,'report.json'),JSON.stringify({...report,sourceRevision:sourceRevision(root)}));return {code:report?.ok?0:1,stdout:''};}return {code:0,stdout:JSON.stringify(valid)};};return {c,sent,failed};}
 await test('browser green cannot bypass a failing configured business flow',async()=>{const f=fixture({ok:false,layers:[{layer:'business',name:'Save',status:'failed'}],findings:[{severity:'error',check:'business',message:'Record not found after reload'}]});await f.c.runBrowserSelfCheck('token');assert.equal(f.c._learningSignals.size,0);assert.equal(f.sent.length,1);assert.match(f.sent[0],/Record not found/);});
 await test('checker without report cannot trigger application rewrites',async()=>{const f=fixture(null);await f.c.runBrowserSelfCheck('token');assert.equal(f.sent.length,0);assert.equal(f.failed.length,1);});
 await test('inconsistent successful report with a failed layer cannot pass or trigger repairs',async()=>{const f=fixture({ok:true,layers:[{layer:'business',name:'Save',status:'failed'}],findings:[]});await f.c.runBrowserSelfCheck('token');assert.equal(f.c._learningSignals.size,0);assert.equal(f.sent.length,0);assert.equal(f.failed.length,1);});
 await test('false result without actionable findings does not become green',async()=>{const f=fixture({ok:false,layers:[{layer:'business',name:'Save',status:'passed'}],findings:[]});await f.c.runBrowserSelfCheck('token');assert.equal(f.c._learningSignals.size,0);assert.equal(f.sent.length,0);assert.equal(f.failed.length,1);});
 await test('configured passing checks publish current evidence',async()=>{const f=fixture({ok:true,layers:[{layer:'design',name:'Home',status:'passed'},{layer:'business',name:'Save',status:'passed'}],findings:[]});await f.c.runBrowserSelfCheck('token');assert.equal(f.c._learningSignals.size,1);const data=projectReadiness(root);assert.equal(data.rows.find(r=>r.id==='business').status,'passed');assert.equal(data.rows.find(r=>r.id==='release').status,'unverified');});
 await test('editing source invalidates all earlier local acceptance',()=>{fs.writeFileSync(path.join(root,'app.js'),'changed');const d=projectReadiness(root);assert.equal(d.ready,false);assert.equal(d.rows.filter(r=>r.status==='stale').length,3);});
 await test('Felix receives project-local contracts and scoped backend verification guidance',()=>{const text=acceptanceContext(root,__dirname);assert.match(text,/design-contract.json/);assert.match(text,/Do not claim API\/auth\/data persistence verified/);assert.match(text,/Never weaken a contract/);});
 console.log(`projectAcceptance.test.js: ${count}/${count} passed`);
}finally{clearTimeout(deadline);fs.rmSync(root,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
