'use strict';
const assert=require('assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const {captureVisualReview,completeVisualReview}=require('./visualReview');const {sourceRevision}=require('./sourceRevision');const {projectReadiness}=require('./projectReadiness');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'felix-review-complete-'));let n=0;
const deadline=setTimeout(()=>{console.error('visual completion timeout');process.exit(1);},5000);
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a7S8AAAAASUVORK5CYII=','base64');
(async()=>{try{
fs.writeFileSync(path.join(root,'index.html'),'<button>Before</button>');const shot=path.join(root,'.solstice','capture.png');fs.mkdirSync(path.dirname(shot),{recursive:true});fs.writeFileSync(shot,png);
const pick=await captureVisualReview(root,{picks:[{selector:'button',text:'Before'}],page:{pathname:'/',viewport:{width:800,height:600}}},async()=>shot);
const file=path.join(root,'.solstice','checks.json'),recordFile=path.join(root,'.solstice','reviews',pick.reviewId,'selection.json');
const write=()=>fs.writeFileSync(file,JSON.stringify({ok:true,url:'http://127.0.0.1:3000',sourceRevision:sourceRevision(root),summary:{linksChecked:1,buttonsChecked:1,formsChecked:0,desktopWidth:1440,mobileWidth:390},findings:[]}));
async function check(name,fn){await fn();n++;console.log('ok - '+name);}
await check('completed review keeps immutable before, route/viewport and measured after revision',async()=>{const before=fs.readFileSync(path.join(path.dirname(recordFile),'before.png'));fs.writeFileSync(path.join(root,'index.html'),'<button>After</button>');write();const result=await completeVisualReview(root,pick.reviewId,file,async record=>{assert.equal(record.page.viewport.width,800);return shot;});assert.equal(result.status,'evidence_ready');assert.deepEqual(fs.readFileSync(path.join(path.dirname(recordFile),'before.png')),before);assert.equal(result.after.sourceRevision.sha256,sourceRevision(root).sha256);assert.equal(projectReadiness(root).reviews[0].status,'evidence_ready');});
await check('repeat check is idempotent; subsequent edit invalidates result',async()=>{await completeVisualReview(root,pick.reviewId,file,()=>assert.fail('must reuse identical evidence'));fs.writeFileSync(path.join(root,'index.html'),'<button>Third</button>');assert.equal(projectReadiness(root).reviews[0].status,'stale');await assert.rejects(completeVisualReview(root,pick.reviewId,file,async()=>shot),/current source/);});
await check('red verification never completes a visual review',async()=>{write();const r=JSON.parse(fs.readFileSync(file));r.ok=false;r.findings=[{severity:'error',check:'broken',message:'broken'}];fs.writeFileSync(file,JSON.stringify(r));await assert.rejects(completeVisualReview(root,pick.reviewId,file,async()=>shot),/passing checks/);});
await check('source race and failed capture preserve original completion',async()=>{write();const before=fs.readFileSync(recordFile);await assert.rejects(completeVisualReview(root,pick.reviewId,file,async()=>{fs.writeFileSync(path.join(root,'index.html'),'changed during capture');return shot;}),/changed during/);assert.deepEqual(fs.readFileSync(recordFile),before);write();await assert.rejects(completeVisualReview(root,pick.reviewId,file,async()=>null),/missing or invalid/);assert.deepEqual(fs.readFileSync(recordFile),before);});
await check('changed evidence and report cannot masquerade as a ready comparison',async()=>{write();await completeVisualReview(root,pick.reviewId,file,async()=>shot);const current=JSON.parse(fs.readFileSync(recordFile));fs.writeFileSync(path.resolve(root,current.after.screenshot),'broken');assert.equal(projectReadiness(root).reviews[0].status,'incomplete');await completeVisualReview(root,pick.reviewId,file,async()=>shot);fs.writeFileSync(file,'{}');assert.equal(projectReadiness(root).reviews[0].status,'incomplete');fs.writeFileSync(path.join(root,'index.html'),'new revision for report race');write();await assert.rejects(completeVisualReview(root,pick.reviewId,file,async()=>{fs.writeFileSync(file,'{}');return shot;}),/report changed/);});
await check('tampered original image blocks completion',async()=>{fs.writeFileSync(path.join(path.dirname(recordFile),'before.png'),'tampered');await assert.rejects(completeVisualReview(root,pick.reviewId,file,async()=>shot),/Before evidence/);});
console.log(`visualCompletion.test.js: ${n}/${n} passed`);
}finally{clearTimeout(deadline);fs.rmSync(root,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
