'use strict';
const assert=require('assert/strict');const {VoiceTranscription}=require('./voiceTranscription');
let n=0;const check=async(name,f)=>{await f();n++;console.log('ok - '+name);};
const deadline=setTimeout(()=>{console.error('voice test timeout');process.exit(1);},8000);
const recording={audio:Buffer.from('fixture-audio').toString('base64'),mime:'audio/webm;codecs=opus',requestId:'one',key:'fixture'};
(async()=>{try{
 await check('Hebrew transcription correlates the recording and preserves model/language',async()=>{let options;const v=new VoiceTranscription({fetchImpl:async(url,o)=>{options=o;return {ok:true,json:async()=>({text:'  תקן את הטופס  '})};}}),out=[];await v.run(recording,m=>out.push(m));assert.equal(options.body.get('language'),'he');assert.equal(options.body.get('model'),'whisper-large-v3');assert.deepEqual(out,[{type:'transcribed',requestId:'one',text:'תקן את הטופס'}]);});
 await check('superseded request cannot deliver late text',async()=>{let first;const v=new VoiceTranscription({fetchImpl:()=>new Promise(r=>{first=r;})}),out=[];const p=v.run(recording,m=>out.push(m));await new Promise(r=>setImmediate(r));v.fetchImpl=async()=>({ok:true,json:async()=>({text:'second'})});await v.run({...recording,requestId:'two'},m=>out.push(m));first({ok:true,json:async()=>({text:'obsolete'})});await p;assert.deepEqual(out.map(x=>x.text),['second']);});
 await check('cancel aborts network and suppresses messages',async()=>{let signal;const v=new VoiceTranscription({fetchImpl:async(u,o)=>{signal=o.signal;return new Promise(()=>{});}}),out=[];const p=v.run(recording,m=>out.push(m));v.cancel();await p;assert.equal(signal.aborted,true);assert.equal(out.length,0);});
 await check('timeout covers stalled response body and frees retry',async()=>{const v=new VoiceTranscription({timeoutMs:20,fetchImpl:async()=>({ok:true,json:()=>new Promise(()=>{})})}),out=[];await v.run(recording,m=>out.push(m));assert.match(out[0].message,/timed out/);assert.equal(v.active,null);v.fetchImpl=async()=>({ok:true,json:async()=>({text:'retry'})});await v.run(recording,m=>out.push(m));assert.equal(out[1].text,'retry');});
 await check('empty speech, provider errors and malformed payload fail explicitly',async()=>{for(const response of [{ok:true,json:async()=>({text:''})},{ok:false,status:429},{ok:true,json:async()=>({text:42})}]){const out=[];await new VoiceTranscription({fetchImpl:async()=>response}).run(recording,m=>out.push(m));assert.equal(out[0].type,'transcribeError');assert.equal(out[0].requestId,'one');}});
 await check('size, mime, base64, missing key and request id rejected before network',async()=>{for(const change of [{audio:'!'},{audio:'AAAA'.repeat(30)},{mime:'text/html'},{key:''},{requestId:''}]){const out=[];await new VoiceTranscription({maxBytes:64,fetchImpl:()=>assert.fail('network must not run')}).run({...recording,...change},m=>out.push(m));assert.equal(out[0].type,'transcribeError');}});
 console.log(`voiceTranscription.test.js: ${n}/${n} passed`);
}finally{clearTimeout(deadline);}})().catch(e=>{console.error(e);process.exitCode=1;});
