'use strict';
const assert=require('assert/strict'),fs=require('fs'),path=require('path');const {chromium}=require('playwright');
const source=fs.readFileSync(path.join(__dirname,'media/panel.js'),'utf8');
const section=source.slice(source.indexOf('\tconst micBtn ='),source.indexOf('\n\tinputEl.addEventListener("keydown"',source.indexOf('\tconst micBtn =')));
let n=0;const deadline=setTimeout(()=>{console.error('voice browser timeout');process.exit(1);},45000);
(async()=>{let browser;try{browser=await chromium.launch({headless:true,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});const page=await browser.newPage();
// Trusted loopback context, actual Chromium MediaRecorder and microphone stream.
const server=require('http').createServer((req,res)=>res.end('<button id="micBtn">🎤</button><textarea id="input"></textarea>'));await new Promise(r=>server.listen(0,'127.0.0.1',r));
try{await page.goto('http://127.0.0.1:'+server.address().port);await page.addScriptTag({content:`const inputEl=document.querySelector('#input');const posted=[],notes=[],sent=[];const vscode={postMessage:m=>posted.push(m)};function sysLine(t){notes.push(t);}function send(){sent.push(inputEl.value);inputEl.value='';cancelVoice();}\n${section}\nwindow.qa={posted,notes,sent,cancelVoice,receiveVoice};`});
async function record(){await page.click('#micBtn');await page.waitForFunction(()=>document.querySelector('#micBtn').classList.contains('recording'));await page.waitForTimeout(150);await page.click('#micBtn');await page.waitForFunction(()=>qa.posted.some(m=>m.type==='transcribe'));return await page.evaluate(()=>qa.posted.filter(m=>m.type==='transcribe').at(-1));}
async function check(name,fn){await fn();n++;console.log('ok - '+name);}
await check('real MediaRecorder captures bytes, releases mic and sends correlated Hebrew brief once',async()=>{const rec=await record();assert.ok(rec.audio.length>20);assert.ok(rec.requestId);await page.evaluate(id=>qa.receiveVoice({type:'transcribed',requestId:id,text:'תקן את הטופס'}),rec.requestId);assert.deepEqual(await page.evaluate(()=>qa.sent),['תקן את הטופס']);await page.evaluate(id=>qa.receiveVoice({type:'transcribed',requestId:id,text:'duplicate'}),rec.requestId);assert.equal(await page.evaluate(()=>qa.sent.length),1);});
await check('cancel rejects late transcript from previous recording',async()=>{await page.evaluate(()=>qa.posted.length=0);const rec=await record();await page.click('#micBtn');await page.evaluate(id=>qa.receiveVoice({type:'transcribed',requestId:id,text:'late'}),rec.requestId);assert.equal(await page.inputValue('#input'),'');assert.equal(await page.evaluate(()=>qa.sent.length),1);});
await check('draft edited during transcription is preserved and not auto-submitted',async()=>{await page.evaluate(()=>qa.posted.length=0);const rec=await record();await page.fill('#input','טיוטה חדשה');await page.evaluate(id=>qa.receiveVoice({type:'transcribed',requestId:id,text:'הוסף כפתור'}),rec.requestId);assert.equal(await page.inputValue('#input'),'טיוטה חדשה הוסף כפתור');assert.equal(await page.evaluate(()=>qa.sent.length),1);});
await check('reset while mic permission is pending releases late stream without recording',async()=>{await page.evaluate(async()=>{let resolve;const original=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);navigator.mediaDevices.getUserMedia=()=>new Promise(r=>resolve=r);document.querySelector('#micBtn').click();qa.cancelVoice();let stops=0;resolve({getTracks:()=>[{stop:()=>stops++}]});await new Promise(r=>setTimeout(r,20));if(stops!==1)throw Error('late microphone not released exactly once');navigator.mediaDevices.getUserMedia=original;});});
await check('thread reset and manual send cancel pending recording in production panel',()=>{assert.match(source,/case "reset":\s+cancelVoice\(\)/);assert.match(source,/function send\(\)[\s\S]*?cancelVoice\(\);[\s\S]*?const steering/);});
await check('a wrong recording id cannot contaminate a new in-flight recording',async()=>{await page.fill('#input','');await page.evaluate(()=>qa.posted.length=0);const rec=await record();const sent=await page.evaluate(()=>qa.sent.length);await page.evaluate(()=>qa.receiveVoice({type:'transcribed',requestId:'wrong-id',text:'טקסט זר'}));assert.equal(await page.inputValue('#input'),'');assert.equal(await page.evaluate(()=>qa.sent.length),sent);await page.evaluate(id=>qa.receiveVoice({type:'transcribed',requestId:id,text:'הנוכחי'}),rec.requestId);assert.equal(await page.evaluate(()=>qa.sent.at(-1)),'הנוכחי');});
console.log(`voiceCapture.test.js: ${n}/${n} passed`);
}finally{server.close();}
}finally{clearTimeout(deadline);await browser?.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
