'use strict';
(()=>{const api=acquireVsCodeApi(),app=document.querySelector('#app');let busy=false;
const labels={passed:'עבר',failed:'נכשל',unverified:'טרם נבדק',stale:'דורש בדיקה חוזרת',open:'מוכן לתיקון',incomplete:'ראיות חסרות · בדוק מחדש',evidence_ready:'בדיקות עברו · ממתין לסקירה'};
const el=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls||'';if(text)n.textContent=text;return n;};
function action(text,type){const b=el('button','action',text);b.disabled=busy;b.onclick=()=>api.postMessage({type});return b;}
function render(data){app.replaceChildren();app.dir='rtl';const main=el('main');
 const header=el('header');header.append(el('div','eyebrow','SOLSTICE / PROJECT READINESS'),el('h1','',data.name||'הפרויקט שלך'),el('p','intro',data.ready?'הבדיקות המקומיות עברו. מסירה להתקנה עדיין דורשת אימות.':'כאן רואים מה עובד, ומה עדיין צריך הוכחה.'));main.append(header);
 const toolbar=el('div','toolbar');toolbar.append(action(busy?'בודק…':'הרץ בדיקות פרויקט','runChecks'),action('פתח פריוויו','openPreview'),action('רענן מצב','refresh'),action('צור בסיס עסקי','scaffoldBusiness'));main.append(toolbar);
 const summary=el('section','summary');summary.append(el('span','version','גרסת קוד · '+String(data.revision?.sha256||'').slice(0,12)),el('span','',data.revision?.files+' קבצים במעקב'),el('span','',data.checkedAt?'בדיקה אחרונה · '+new Date(data.checkedAt).toLocaleString('he-IL'):'ממתין להרצה ראשונה'));main.append(summary);
 const grid=el('div','grid');for(const row of data.rows||[]){const card=el('article','card '+row.status);const top=el('div','cardTop');top.append(el('span','badge '+row.status,labels[row.status]),el('span','step','0'+((data.rows||[]).indexOf(row)+1)));card.append(top,el('h2','',row.label),el('p','detail',row.detail));for(const c of row.checks||[]){card.append(el('div','check '+c.status,(c.status==='passed'?'✓ ':'· ')+c.name));}grid.append(card);}main.append(grid);
 if(data.findings?.length){const section=el('section','findings');section.append(el('h2','','ממצאים לתיקון'));for(const f of data.findings)section.append(el('p','',f.message));main.append(section);}
 const shots=el('section','shots');for(const shot of data.screenshots||[]){if(!shot.uri)continue;const figure=el('figure');const img=el('img');img.src=shot.uri;img.alt=shot.name+' · '+shot.size;figure.append(img,el('figcaption','',img.alt));shots.append(figure);}if(shots.childNodes.length)main.append(el('h2','','ראיות מההרצה'),shots);
 if(data.reviews?.length){main.append(el('h2','','תיקונים חזותיים'));for(const r of data.reviews){const card=el('div','review');card.append(el('span','badge '+r.status,labels[r.status]),el('code','',r.label));const pair=el('div','shots');for(const [label,uri] of [['לפני',r.beforeUri],['אחרי',r.afterUri]]){if(!uri)continue;const figure=el('figure'),img=el('img');img.src=uri;img.alt=label+' · '+r.label;figure.append(img,el('figcaption','',label));pair.append(figure);}card.append(pair,el('p','detail','השווה את התוצאה לבקשה. צילום ובדיקות אינם אישור חזותי אוטומטי.'));main.append(card);}}
 const foot=el('footer');foot.append(el('strong','','היקף האימות'),el('p','','בדיקות מסכים ותרחישים מוגדרים בלבד. שירותים חיצוניים, התקנת Windows/Mac ופרסום אינם מוסקים מתוצאה מקומית.'));main.append(foot);app.append(main);}
window.addEventListener('message',e=>{if(e.data.type==='readiness'){busy=!!e.data.busy;render(e.data.data);}if(e.data.type==='error'){let n=document.querySelector('.error');if(!n){n=el('p','error');app.prepend(n);}n.textContent=e.data.message;}});api.postMessage({type:'refresh'});
})();
